Brute force
WilgelmFlower/BruteForce pull request #2
Opened 2022-07-14 13:46 UTC by WilgelmFlower

check it now)

2022-07-16 17:29 UTC, daganov requested changes
Привет. Всё работает, но исправь структуру программы. Свойства и методы не должны находиться в глобальной области видимости.
Всё, что касается подбора пароля должно находится в собственном модуле.

2022-07-16 17:29 UTC, daganov commented on BruteForce/Sources/App/SceneDelegate.swift
> +
Убирай лишние пустые строки

2022-07-16 17:29 UTC, daganov commented on BruteForce/Sources/Scenes/Controller/Properties.swift
> +}()
Любая переменная должна принадлежать какому-то объекту. Эти элементы у тебя относятся к вьюконтроллеру, выносить их в отдельный файл нет необходимости, ещё и в глобальную область видимости.

2022-07-16 17:29 UTC, daganov commented on BruteForce/Sources/Scenes/Controller/ViewController.swift
> +
Убирай лишние пустые строки

2022-07-16 17:29 UTC, daganov commented on BruteForce/Sources/Scenes/Controller/ViewController.swift
> +    }
Этот метод не имеет никакого отношения к вьюконтроллеру

2022-07-16 17:29 UTC, daganov commented on BruteForce/Sources/Scenes/Controller/ViewController.swift
> +    }
Этот метод не имеет никакого отношения к вьюконтроллеру

2022-07-16 17:29 UTC, daganov commented on BruteForce/Sources/Scenes/Model/BruteForce.swift
> +}
Эти методы у тебя относятся к подбору пароля. Они не должны быть в глобальной области видимости.

2022-07-17 17:21 UTC, WilgelmFlower commented
close

2022-07-17 17:21 UTC, closed without merging